# Generated by Django 2.2.2 on 2019-06-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dni', models.CharField(max_length=12)),
                ('Apellido', models.CharField(max_length=70)),
                ('Nombre', models.CharField(max_length=70)),
                ('Pais', models.CharField(max_length=70)),
                ('FechaNacimiento', models.DateField()),
            ],
        ),
    ]
