# Generated by Django 2.2.2 on 2019-06-19 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTrabajadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=70)),
            ],
        ),
        migrations.RenameField(
            model_name='trabajador',
            old_name='Apellido',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='trabajador',
            old_name='FechaNacimiento',
            new_name='fechaNacimiento',
        ),
        migrations.RenameField(
            model_name='trabajador',
            old_name='Nombre',
            new_name='nombres',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='Dni',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='Pais',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='id',
        ),
        migrations.AddField(
            model_name='trabajador',
            name='dni',
            field=models.CharField(default=12547852, max_length=12, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajador',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionTrabajadores.Pais'),
        ),
    ]
