# Generated by Django 2.2.2 on 2019-06-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTrabajadores', '0002_auto_20190619_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='foto',
            field=models.ImageField(default='photos/user.jpg', upload_to='photos'),
        ),
    ]
